import LeanBourbaki.TheoryOfSets.LogicalTheories
import LeanBourbaki.TheoryOfSets.QuantifiedTheories
import LeanBourbaki.TheoryOfSets.EqualitarianTheories
import LeanBourbaki.TheoryOfSets.CollectivizingRelations
import LeanBourbaki.TheoryOfSets.OrderedPairs
